version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: ${DOCKER_HUB_USERNAME}/openstudy-backend:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  fastapi:
    image: ${DOCKER_HUB_USERNAME}/openstudy-fastapi:latest
    restart: always
    ports:
    - '8000:8000'
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    networks:
      - app-network

  angular:
    image: ${DOCKER_HUB_USERNAME}/openstudy-angular:latest
    restart: always
    ports:
    - '4200:80' 
    depends_on:
      - backend
      - fastapi
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
